keys:
  - &cherr age14nhh2y6vy0jgpq6h2uzl5hu0tkd4aqewx77hcyu0arxmt8ee9s3sw0vq3m
  - &host age1lq8xn4mhder3dne4uq9s49w3vx8ml50yq0v7y5dt88avz7dujs4q7vavtq
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *cherr
          - *host
