name: Check NixOS Config

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          extra-conf: |
            accept-flake-config = true

      - name: flake check
        run: nix flake check

      - name: build system closure
        run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel -L
